### PR TITLE
Beatyfixes

### PR DESCRIPTION
**Pull request by TimRepke**
I found some glitches in your code and fixed them.
- play/pause button not shown
- bloated volume control
- scrolling track title just flickering
- redundant use of timeouts/intervals

hope you are happy with the changes.

### CODE REVIEW

**Comment by TimRepke** [comment]
@BirgitPohl feel free to use the updates and merge ;)

**Comment by BirgitPohl** [comment]
Ui. Thank you very much. I really appreciate your contribution. Hehe.
I'll leave it here for now, because I may need the comments I made in the code later. Hehe.

**Comment by TimRepke** [comment]
The great thing about git: it has a history :P
(you will easily find this PR again or you could set a flag)

**Comment by BirgitPohl** [comment]
Yes. I thought about it a couple of times during the last months, it just didn't want to go out of my head. Therefore, yes, you are right. Let's merge it. :)

**Pull request merged**
